version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lara_cloud
    volumes:
      - ./src/main/resources/data/init.sql:/docker-entrypoint-initdb.d/init.sql
  k3s:
    image: rancher/k3s
    privileged: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    command: server -https-listen-port=6443
    ports:
      - '6443:6443'
    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - ./src/main/resources/k3s-compose-output:/output
      - ./src/main/resources/k3s-manifests:/var/lib/rancher/k3s/server/manifests

volumes:
  k3s-server: